In [2]:
import numpy as np
a=np.arange(1,21)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [12]:
np.random.seed(0)
x=np.random.randint(50,size=(4,5))
print(x)
print(x.nbytes)
print(x.itemsize)

[[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]
80
4


In [26]:
arr=np.arange(1,13).reshape(3,4)
print(arr[2,3])
print(arr[-1])
print(arr[:,-1])

12
[ 9 10 11 12]
[ 4  8 12]


In [31]:
x=np.arange(1,13)
y=x.reshape(3,4)
z=x.reshape(12,1)
a=x[:,np.newaxis]
print(y)
print(z)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [7]:
x=np.arange(1,13).reshape(3,4)
a=x[:2,:2]
b=x[:,::2]
c=x[:,::-1]
print(a)
print(b)
print(c)

[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [8]:
x=np.arange(1,21).reshape(4, 5)
a=x[:3,:4]
a[0,0]=100
print(a)
print(x)
b=x[:3,:4].copy()
b[0,0]=200
print(b)
print(x)

[[100   2   3   4]
 [  6   7   8   9]
 [ 11  12  13  14]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[200   2   3   4]
 [  6   7   8   9]
 [ 11  12  13  14]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [6]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(2,3))
print(a)
print(b)
c=np.vstack((a,b))
d=np.concatenate((a,b),axis=0)
print(c)
print(d)
e=np.hstack((a,b))
f=np.concatenate((a,b),axis=1)
print(e)
print(f)

[[6 8 6]
 [1 1 6]]
[[9 3 7]
 [4 7 9]]
[[6 8 6]
 [1 1 6]
 [9 3 7]
 [4 7 9]]
[[6 8 6]
 [1 1 6]
 [9 3 7]
 [4 7 9]]
[[6 8 6 9 3 7]
 [1 1 6 4 7 9]]
[[6 8 6 9 3 7]
 [1 1 6 4 7 9]]


In [9]:
x=np.arange(1,16)
print(x)
a=np.split(x,3)
print(a[0])
print(a[1])
print(a[2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
x=np.arange(1,25).reshape(6,4)
print(x)
a=np.hsplit(x,2)
print(a[0])
print(a[1])
b=np.vsplit(x,2)
print(b[0])
print(b[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
