In [ ]:
import numpy as x
arr=x.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
b=x.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
a=x.array([7,8,9],dtype=float)
print(a)
print(type(a))

[7. 8. 9.]
<class 'numpy.ndarray'>


In [ ]:
c=x.zeros(6)
d=x.ones((2,3),dtype=int)
print(c)
print(d)

[0. 0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]]


In [ ]:
e=x.empty((2,2))
print(e)

[[1.89463822e-315 0.00000000e+000]
 [9.08587368e-304 1.04225969e-032]]


In [ ]:
f=x.arange(0,20,2)
g=x.linspace(0,1,6)
print(f)
print(g)

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]
